### ISSUE TITLE
Project Status

### ISSUE THREAD

**Issue by sean-owen** [Fibula-MMO/fibula-server#1]
@jlnunez89 Hi Jose,

I have cloned the repo and run up the project. It appeared that walking on stairs did not take you to another floor & using of containers / ladders was not working.

It would be good if you could create a project status issue with a general project status and maybe a list of ToDo's for the project.
From there maybe I can look at breaking out that list into separate issues with a description of the changes needed?

From a quick google it looks like you are probably familiar with agile working since you work at Microsoft.

I think it would be good if we could get issues setup looking like stories that contributors can pull off and work on. This would be helpful for me at least :)

**Comment by sean-owen** [comment]
I can see in the old repository you did have a project board. Would be good if that got migrated over!

**Comment by jlnunez89** [comment]
Yeah apparently that doesn't import when I imported the project over to the org repo. In any case that one needs a rewrite, hehe. I'll try to set it up and add some cards that make sense with what the current project status is :)

Regarding the stairs and such, those are not actually enabled, because of the way they are scripted in the Cip assets files: that functionality comes from the [moveuse.dat](https://github.com/Fibula-MMO/fibula-server/blob/master/data/config/moveuse.dat) file and, while I'd written some code to parse and enable the scripts in it, I didn't quite like the way I had implemented it and decided to strip all that and redesign it in one of the several refactors the code has been through (about 2 or 3 major refactors, hehe).

I think what's next in my mental list is to standardize the stats and skills on creatures (including the formula for counts i.e. how many hits or experience do I need to advance to the next level). 

Then I'd focus on the inventory loading of both players and monsters on creation, and then probably either some actual combat system/ hit formula etc, or at least some persistence to or load from some storage (files/sql/sqlite/cosmosdb).
 
After that I was hoping to focus on implementing spells and runes, to make combat more appealing and after that actually open the server on an alpha test server, to gain some traction in the community and get more people to test it.
